### ISSUE TITLE
Adding user ID to log

### ISSUE THREAD

**Issue by EriksonEnterprises** [djokicpn/laravel-email-audit-log#1]
Is there any way to log which user ID the email sent from?

**Comment by djokicpn** [comment]
Thanks for the feedback. Adding it to the next release. Probably will do it later today!

**Comment by EriksonEnterprises** [comment]
> Thanks for the feedback. Adding it to the next release. Probably will do it later today!

Thank you so much!

I was able to upgrade the version and I see the new migration. LOVE IT!

**Comment by djokicpn** [comment]
> > Thanks for the feedback. Adding it to the next release. Probably will do it later today!
> 
> Thank you so much!
> 
> I was able to upgrade the version and I see the new migration. LOVE IT!

Just update package to latest version, publish migrations (`php artisan vendor:publish --tag=email-audit-log-migrations `) and `php artisan migrate`

**Comment by EriksonEnterprises** [comment]
> > > Thanks for the feedback. Adding it to the next release. Probably will do it later today!
> > 
> > 
> > Thank you so much!
> > I was able to upgrade the version and I see the new migration. LOVE IT!
> 
> Just update package to latest version, publish migrations (`php artisan vendor:publish --tag=email-audit-log-migrations `) and `php artisan migrate`

All good thanks!

Is there any way to pass the User ID if there is no logged in user but there's a form being submitted?

For instance, I have this public form that people can choose to "sign up" to a waitlist for a certain user (lets say user ID 2)

They get an initial email saying thank you for signing up, I was curious if there's a way I can pass the `User ID of #2` so I can add that to `User ID #2's` history (or whichever user the public signs up to)

This may be too specific of a usage condition though, so I understand if not, especially since this mainly goes off the Mail::to command. Maybe I can just update the email log user_id column to the most recent row with the submitted guest email address, that may be the best way

Thank you
