### ISSUE TITLE
remove [" "] from to database field

### ISSUE THREAD

**Issue by EriksonEnterprises** [djokicpn/laravel-email-audit-log#3]
Hello,

Not sure if this is possible or not

Every email address in the `to` column in database has [" "]

Example:

`["example@domain.com"]`

Is there any way to disable the [" "] from being added? So it'll be this instead:

`example@domain.com`

I haven't tested the `cc` field yet, but I'm assuming it'll happen in there too

Thank you

**Comment by localpath** [comment]
@jamesautodude the `to` field can support multiple addresses so storing it as an array of strings is a proper way to handle that, same as `cc` or `bcc` fields. If you parse the resulting field as json you would get structured data back.

Just a helpful thought.

**Comment by EriksonEnterprises** [comment]
> @jamesautodude the `to` field can support multiple addresses so storing it as an array of strings is a proper way to handle that, same as `cc` or `bcc` fields. If you parse the resulting field as json you would get structured data back.
> 
> Just a helpful thought.

Okay I'll do that. Thank you
