### ISSUE TITLE
Incorrect down method for migration

### ISSUE THREAD

**Issue by EriksonEnterprises** [djokicpn/laravel-email-audit-log#4]
Hello, I get an error when running `migrate:refresh`

Error is in:

`2023_01_01_205102_djokicpn_add_user_id_to_log_table`

Error code:
`Call to undefined method Illuminate\Database\Schema\MySqlBuilder::dropForeign()`

To fix this, must change lines to:

```
public function down()
{
    Schema::table('email_audit_log', function (Blueprint $table) {
        $table->dropForeign(['email_audit_log_user_id_foreign']);
        $table->dropColumn('user_id');
    });
}
```

I tried to change that myself for my end, but for some reason my changes don't take effect in my project?? Still has the same error. I even deleted the whole migration file and somehow it still tries to run the `2023_01_01_205102_djokicpn_add_user_id_to_log_table`

**Comment by EriksonEnterprises** [comment]
You can also use:
`$table->dropConstrainedForeignId('user_id');`

**Comment by djokicpn** [comment]
@jamesautodude sorry for late reply. I didnt update project, will do later this week! Thanks for issue!
