### ISSUE TITLE
Call to undefined method Illuminate\Database\Schema\MySqlBuilder::dropForeign()

### ISSUE THREAD

**Issue by EriksonEnterprises** [djokicpn/laravel-email-audit-log#7]
In the migration named `2023_01_01_205102_djokicpn_add_user_id_to_email_audit_log_table`, when you do:

`php artisan migrate:refresh` or `php artisan migrate:rollback`, you get the following error:

`Call to undefined method Illuminate\Database\Schema\MySqlBuilder::dropForeign()`

The fix is to replace the Down method with:
```
Schema::table('email_audit_log', function (Blueprint $table) {
$table->dropForeign('user_id');
});
```

I have tried doing this manually, but for some reason the published migrations are ignored for your package.

**Comment by djokicpn** [comment]
thanks @jamesautodude I could replicate issue on my side. It will be fixed in new release that i play for end of the week! Thanks ! :)

**Comment by blessingdube** [comment]
Hey guys! I created a PR to fix this here:
https://github.com/djokicpn/laravel-email-audit-log/pull/9

**Comment by djokicpn** [comment]
Merged! Thanks 👍

**Comment by blessingdube** [comment]
> Merged! Thanks 👍  

Hey @djokicpn, just a heads up - you might need to do a release for the changes in this PR to apply 🙂
